exclude: ["Gemfile", "Gemfile.lock", "jekyll.sh", "configurator", "vendor"]
plugins:
  - jekyll-paginate
highlighter: rouge
markdown: kramdown

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: http://www.inbucket.org

# Site-wide variables
name: Inbucket
navbar:
  - {group: news, label: "News", path: "/news/"}
  - {group: about, label: "About", path: "/about/"}
  - {group: screenshots, label: "Screenshots", path: "/screenshots/"}

# Blog Config
permalink: /news/:year/:month/:title.html
paginate: 5
paginate_path: "news/page:num"

# Binaries
binary_versions: ["1.3.0", "1.3.1", "2.0.0-rc1"]
binary_base: https://github.com/jhillyerd/inbucket/releases/download
binary_platforms:
  - label: "Apple Mac"
    name: darwin
    architectures:
      - {name: amd64, ext: tar.gz}
  - label: "FreeBSD"
    name: freebsd
    architectures:
      - {name: amd64, ext: tar.gz}
  - label: "Linux"
    name: linux
    architectures:
      - {name: amd64, ext: tar.gz}
  - label: "MS Windows"
    name: windows
    architectures:
      - {name: amd64, ext: zip}

# - {name: amd64, ext: deb}
# - {name: amd64, ext: rpm}
