name = "configurator"
version = "1.0.0"
target = "javascript"

gleam = ">= 1.9.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.0.3 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.8.0 and < 2.0.0"
